
server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.186.129:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置 Nacos Server 地址
  application:
    name: mall-order
  rabbitmq:
    host: 124.220.57.29
    port: 5672
    virtual-host: /
    publisher-confirms: true # 开启发送端确认
    publisher-returns: true # 开启发送端消息抵达队列的确认
    template:
      mandatory: true # 只要抵达队列, 以异步发送模式优先回调我们的这个returnConfirm

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config: # 配置数据库实体类主键自增, 否则需要在每个实体类上操作
    db-config:
      id-type: auto
